#!/usr/bin/python3

target = 20000

def main():
    f = 1
    c = 1

    while c < target:
        f *= c
        c += 1

    while c != 1:
        c -= 1
        f //= c

    s = hex(f)[2:]
    print(s, end='')

if __name__ == "__main__":
    main()
