#!/usr/bin/python3

target = 200000

def main():
    f0 = 1
    f1 = 1

    for i in range(target):
        f0 = f0 + f1
        f1 = f0 - f1

    s = hex(f0)[2:]
    print(s, end='')

if __name__ == "__main__":
    main()
